/**
 * markdownPlan.ts
 * Renders a RampUpPlan into a human-readable Markdown document.
 * Returned as a string; served by the API at
 * GET /api/onboarding/plan/:planId/markdown
 */

import { RampUpPlan, RampUpTask } from '../orchestrator/planner.js';

const PRIORITY_BADGE: Record<string, string> = {
  high:   '🔴 HIGH',
  medium: '🟡 MEDIUM',
  low:    '🟢 LOW',
};

const DAY_THEME: Record<number, string> = {
  1: 'Orientation & Tooling',
  2: 'Core Architecture Deep-Dive',
  3: 'Hands-On Integration',
  4: 'Domain Mastery',
  5: 'Independent Contribution',
};

function renderTask(task: RampUpTask, index: number): string {
  const badge     = PRIORITY_BADGE[task.priority] ?? task.priority.toUpperCase();
  const verified  = task.verified ? '✅' : '❌';
  const hours     = `⏱ ${task.estimatedHours}h`;
  const paths     = task.filePaths.length > 0
    ? `\n**Files:** \`${task.filePaths.join('`  `')}\``
    : '';
  const issueRef  = task.historicalIssueRef
    ? `\n> 📖 **Historical reference:** ${task.historicalIssueRef}`
    : '';
  const staleNote = !task.verified && task.verificationNote
    ? `\n> ⚠️  ${task.verificationNote}`
    : '';
  const confidence = `\n*Confidence: ${Math.round((task.confidence ?? 1) * 100)}%*`;

  return (
    `### ${index}. ${verified} ${task.title}\n\n` +
    `${badge} · ${hours}\n\n` +
    `${task.description}${paths}${issueRef}${staleNote}${confidence}\n`
  );
}

function groupByDay(tasks: RampUpTask[]): Map<number, RampUpTask[]> {
  const map = new Map<number, RampUpTask[]>();
  for (const task of tasks) {
    const day = map.get(task.day) ?? [];
    day.push(task);
    map.set(task.day, day);
  }
  return map;
}

export function renderMarkdown(plan: RampUpPlan): string {
  const lines: string[] = [];
  const role            = plan.role.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const generated       = new Date(plan.generatedAt).toLocaleString('en-GB', { timeZone: 'Africa/Nairobi' });

  lines.push(`# i3 Agentic AI Labs — ${role} Onboarding Plan`);
  lines.push('');
  lines.push(`> **Generated:** ${generated} EAT`);
  lines.push(`> **Verified tasks:** ${plan.totalVerified} · **Needs verification:** ${plan.totalUnverified}`);
  lines.push('');

  // Stale doc warnings
  if (plan.staleDocWarnings.length > 0) {
    lines.push('## ⚠️ Stale Documentation Warnings');
    lines.push('');
    for (const w of plan.staleDocWarnings) {
      lines.push(`- \`${w}\``);
    }
    lines.push('');
  }

  // Architectural summary
  const arch = plan.architecturalSummary;
  lines.push('## 🏗 Architectural Summary');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Cluster | ${arch.clusterVersion} |`);
  lines.push(`| Region  | ${arch.region} |`);
  lines.push(`| Namespaces | ${arch.namespaceCount} managed |`);
  lines.push(`| Credit Budget | ${arch.creditBudget} |`);
  lines.push('');

  lines.push('**Key Services:**');
  for (const svc of arch.keyServices) {
    lines.push(`- ${svc}`);
  }
  lines.push('');

  lines.push('**⛔ Forbidden Actions:**');
  for (const fa of arch.forbiddenActions) {
    lines.push(`- ${fa}`);
  }
  lines.push('');

  // 5-day plan
  lines.push('## 📅 5-Day Ramp-Up Plan');
  lines.push('');

  const byDay = groupByDay(plan.tasks);
  let globalIdx = 1;

  for (let day = 1; day <= 5; day++) {
    const tasks  = byDay.get(day) ?? [];
    const theme  = DAY_THEME[day] ?? '';
    const hours  = tasks.reduce((sum, t) => sum + t.estimatedHours, 0);

    lines.push(`## Day ${day}: ${theme}`);
    lines.push(`*${tasks.length} task${tasks.length !== 1 ? 's' : ''} · ~${hours}h total*`);
    lines.push('');

    if (tasks.length === 0) {
      lines.push('*No tasks assigned for this day.*');
      lines.push('');
      continue;
    }

    for (const task of tasks) {
      lines.push(renderTask(task, globalIdx++));
    }
  }

  lines.push('---');
  lines.push('*Generated by i3 Onboarding Agent · IBM TechXchange Hackathon 2026*');

  return lines.join('\n');
}
