-- ============================================================
-- Migration: 012_set7_exam_retake_rules.sql
--
-- 1. Add retake_window_hours column to exams table to enforce
--    time-gated retake windows per exam.
-- 2. Insert/update the C1000-207 SET 7 exam record with:
--      - max_attempts = 3 (1 initial + 2 retakes)
--      - pass_threshold = 90.0 (90%)
--      - retake_window_hours = 48 (retakes must be within 48h)
-- 3. Seed all 60 Set 7 questions.
-- 4. Add retake_window_hours enforcement index.
-- ============================================================

BEGIN;

-- ═══════════════════════════════════════════════════════════════
-- 1. Schema: retake_window_hours on exams
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE exams
  ADD COLUMN IF NOT EXISTS retake_window_hours INT DEFAULT NULL;
-- NULL = no retake window (open policy); set a value to enforce a window.

COMMENT ON COLUMN exams.retake_window_hours IS
  'If set, each retake attempt must be started within this many hours of the first attempt start. NULL = no restriction.';

-- ═══════════════════════════════════════════════════════════════
-- 2. Insert/upsert Set 7 exam record
--    • max_attempts = 3 (initial + 2 retakes)
--    • pass_threshold = 90%
--    • retake_window_hours = 48 (48h window per retake pair)
--    • duration_secs = 5400 (90 minutes)
-- ═══════════════════════════════════════════════════════════════

INSERT INTO exams (
  id,
  title,
  code,
  description,
  duration_secs,
  pass_threshold,
  max_attempts,
  retake_window_hours,
  randomize_order,
  tags,
  is_published,
  tenant_id
)
VALUES (
  gen_random_uuid(),
  'IBM watsonx Orchestrate C1000-207 — Practice Set 7',
  'C1000-207-SET7',
  'Advanced 60-question practice set covering all 7 watsonx Orchestrate domains: Platform Architecture, Agent & Assistant Integration, Workflow Design, Agent Development, Model Management, Security & Compliance, and Deployment & Resiliency. Pass at 90% to proceed.',
  5400,
  90.0,
  3,
  48,
  true,
  ARRAY['C1000-207','watsonx-orchestrate','advanced','set-7'],
  true,
  '00000000-0000-0000-0000-000000000002'
)
ON CONFLICT (code) DO UPDATE
  SET pass_threshold      = EXCLUDED.pass_threshold,
      max_attempts        = EXCLUDED.max_attempts,
      retake_window_hours = EXCLUDED.retake_window_hours,
      description         = EXCLUDED.description,
      is_published        = true;

-- ═══════════════════════════════════════════════════════════════
-- 3. Seed Set 7 questions (60 questions)
--    We DELETE existing set_number=7 questions first (idempotent re-run).
-- ═══════════════════════════════════════════════════════════════

DELETE FROM questions WHERE set_number = 7;

INSERT INTO questions (
  id, stem, text, type, question_type, options, correct_answers,
  explanation, domain_number, domain_name, set_number, question_number,
  difficulty, is_active
) VALUES

-- Q1
(gen_random_uuid(),'A hybrid enterprise runs watsonx Orchestrate on-premises against Software Hub while also piloting a second tenant on IBM Cloud SaaS. A consultant claims that because Software Hub already provides identity, storage, and licensing, the SaaS tenant must also be provisioned against the customer''s own Software Hub instance. Why is this claim incorrect?','A hybrid enterprise runs watsonx Orchestrate on-premises against Software Hub while also piloting a second tenant on IBM Cloud SaaS. A consultant claims that because Software Hub already provides identity, storage, and licensing, the SaaS tenant must also be provisioned against the customer''s own Software Hub instance. Why is this claim incorrect?','MC','mcq','["Software Hub cannot be licensed for on-premises use at all, so the on-prem tenant is invalid","In SaaS deployments (IBM Cloud, AWS Marketplace) IBM manages the underlying hosting substrate itself, so the SaaS tenant does not depend on the customer''s own Software Hub instance the way the hybrid/on-prem tenant does","Software Hub is only a billing dashboard and has no bearing on either deployment model","AWS Marketplace deployments are not supported, so the comparison is moot"]',ARRAY['B'],'Software Hub is the licensing/compute/identity substrate Orchestrate depends on for hybrid and on-prem installs. For SaaS delivery IBM manages that substrate, so the two models are not interchangeable.',1,'Platform Architecture and Core Concepts',7,1,'intermediate',true),

-- Q2
(gen_random_uuid(),'A process owner describes a workflow as: fixed set of approval steps, inputs always arrive in the same structured format from the same three systems, and the outcome is always one of two predictable states. A second workflow is described as: an underwriter reviewing an unusual claim using judgment that changes case-by-case with no repeatable pattern. Which statement correctly scopes these two for watsonx Orchestrate?','A process owner describes a workflow as: fixed set of approval steps, inputs always arrive in the same structured format from the same three systems, and the outcome is always one of two predictable states. A second workflow is described as: an underwriter reviewing an unusual claim using judgment that changes case-by-case with no repeatable pattern. Which statement correctly scopes these two for watsonx Orchestrate?','MC','mcq','["Both are equally good candidates because Orchestrate can add human-in-the-loop steps to any process","Neither is suitable because Orchestrate only automates processes with zero human involvement","The first is a strong candidate (repetitive, rule-based, standardized inputs, predictable outcomes); the second is generally NOT suitable because it is unstructured, case-by-case judgment with no repeatable steps","The second is the stronger candidate because Orchestrate specializes in ambiguous, judgment-driven decision-making"]',ARRAY['C'],'Suitable processes are repetitive, rule-based, multi-step, with standardized inputs and predictable outcomes. Unstructured, case-by-case judgment calls are explicitly NOT suitable.',1,'Platform Architecture and Core Concepts',7,2,'intermediate',true),

-- Q3
(gen_random_uuid(),'Select ALL statements below that correctly describe a documented core capability of the watsonx Orchestrate platform (as opposed to a capability that sounds plausible but is not part of the documented core set).','Select ALL statements below that correctly describe a documented core capability of the watsonx Orchestrate platform (as opposed to a capability that sounds plausible but is not part of the documented core set).','MR','multi_select','["Environments (Dev, Test, Prod) that isolate configuration and agent versions across a promotion lifecycle","An AI Gateway with model policies for routing, failover, and guardrails across LLM/embedding providers","A built-in payroll disbursement engine that issues employee paychecks directly","A Catalog of reusable, governed assets such as pre-built domain agents and connectors","A native video-rendering engine used to generate marketing explainer videos"]',ARRAY['A','B','D'],'Environments, AI Gateway/model policies, and the Catalog of reusable assets are documented core capabilities. Payroll disbursement and native video rendering are not.',1,'Platform Architecture and Core Concepts',7,3,'advanced',true),

-- Q4
(gen_random_uuid(),'During process analysis prior to automation, a team has already identified the process triggers, actors, systems, and required data. According to the recommended analysis sequence, which activity should they now perform BEFORE finalizing the automation design?','During process analysis prior to automation, a team has already identified the process triggers, actors, systems, and required data. According to the recommended analysis sequence, which activity should they now perform BEFORE finalizing the automation design?','MC','mcq','["Recognize dependencies and handoffs, and determine required decisions, approvals, and conditions, before identifying desired outcomes and success metrics","Skip directly to selecting an LLM, since decisions and approvals are a Section 4 concern","Finalize the chosen channel first, since channel selection determines which decisions and approvals are required","Defer dependency/handoff analysis until after Prod deployment"]',ARRAY['A'],'The recommended analysis sequence after triggers/actors/systems/data is to recognize dependencies and handoffs, then determine required decisions/approvals/conditions, and finally identify desired outcomes — all before design is finalized.',1,'Platform Architecture and Core Concepts',7,4,'intermediate',true),

-- Q5
(gen_random_uuid(),'A partner argues: "Since watsonx Orchestrate can call external tools and knowledge bases, it is functionally equivalent to a platform for building custom machine learning pipelines from raw, unlabeled data." What is the strongest reason this argument is flawed?','A partner argues that watsonx Orchestrate is functionally equivalent to a platform for building custom ML pipelines from raw, unlabeled data. What is the strongest reason this argument is flawed?','MC','mcq','["Orchestrate cannot call external tools, only internal ones","Building a custom ML pipeline from raw data is explicitly listed among scenarios NOT suitable for Orchestrate, which orchestrates existing agents/tools/models rather than performing ground-up model training","Knowledge Bases are only usable in the Dev environment","Orchestrate requires GPUs for every deployment"]',ARRAY['B'],'Highly custom ML pipeline development is explicitly NOT suitable for Orchestrate, which is designed to coordinate existing agents, tools, and models.',1,'Platform Architecture and Core Concepts',7,5,'intermediate',true),

-- Q6
(gen_random_uuid(),'Governance, scalability, and security are described as cutting across the platform''s core capabilities rather than being confined to a single capability. Which statement most accurately reflects this?','Governance, scalability, and security are described as cutting across the platform''s core capabilities rather than being confined to a single capability. Which statement most accurately reflects this?','MC','mcq','["Governance applies only once an agent reaches the Prod environment; Dev and Test are ungoverned by design","Governance, scalability, and security considerations apply consistently across agents, tools, workflows, knowledge bases, and the AI Gateway — not merely to one capability","Security applies only to External Agents, since native agents are inherently trusted","Scalability is solely a property of Knowledge Bases"]',ARRAY['B'],'These considerations apply across ALL core capabilities of the platform, not to one environment or agent type.',1,'Platform Architecture and Core Concepts',7,6,'intermediate',true),

-- Q7
(gen_random_uuid(),'A skeptical architect insists "watsonx Orchestrate is really just one product with one deployment option, so our multi-cloud strategy is irrelevant." Which of the following correctly counter that claim by identifying valid, documented deployment contexts?','A skeptical architect insists watsonx Orchestrate has only one deployment option. Which of the following correctly counter that claim?','MR','multi_select','["IBM Cloud SaaS","AWS Marketplace","On-premises/hybrid via Software Hub","A fully offline desktop installer with no environment concept"]',ARRAY['A','B','C'],'Orchestrate is delivered via IBM Cloud SaaS, AWS Marketplace, and on-premises/hybrid through Software Hub. A fully offline desktop installer is not documented.',1,'Platform Architecture and Core Concepts',7,7,'intermediate',true),

-- Q8
(gen_random_uuid(),'Two engineers disagree about Tools versus Connections. Engineer A says "a Connection performs the actual action, while a Tool merely stores the credentials." Engineer B says the opposite. Which is the correct relationship?','Two engineers disagree about Tools versus Connections. Engineer A says a Connection performs the actual action while a Tool stores credentials. Engineer B says the opposite. Who is correct?','MC','mcq','["Engineer A is correct: Connections execute actions; Tools are passive credential stores","Engineer B is correct: a Tool is the discrete callable capability (the action), while a Connection is the secured credential/endpoint object that lets Tools and Agents reach external systems","Both are correct, since Tools and Connections are interchangeable terms","Neither is correct, because Connections and Tools are both exclusively properties of Knowledge Bases"]',ARRAY['B'],'A Tool is the discrete callable capability; a Connection is the credential/endpoint object used by a Tool (or Agent) to reach an external system.',1,'Platform Architecture and Core Concepts',7,8,'intermediate',true),

-- Q9
(gen_random_uuid(),'A supervisor agent must delegate a subtask to a fraud-detection capability on a separate vendor''s platform, built with a different framework, that must never be re-implemented natively for compliance reasons. Which construct correctly describes this integration?','A supervisor agent must delegate a subtask to a fraud-detection capability on a separate vendor''s platform that must never be re-implemented. Which construct is correct?','MC','mcq','["Correct: Collaborator Agent, because any delegated subtask is by definition a Collaborator Agent","Correct: External Agent configured via A2A using the ADK, because it resides outside WXO on another vendor''s platform; Collaborator Agent is the tempting-but-wrong choice","Correct: Knowledge Base, because compliance rules should be encoded as retrievable documents","Correct: AI Gateway routing rule, because cross-vendor delegation is purely a model-routing concern"]',ARRAY['B'],'An agent hosted on another vendor''s platform integrated via A2A and the ADK is an External Agent. Collaborator Agent describes a WXO-native asset invoked internally.',2,'Agent and Assistant Integration',7,9,'advanced',true),

-- Q10
(gen_random_uuid(),'Which of the following are named, valid sources of agents that can participate in Multi-Agent Orchestration within watsonx Orchestrate? Select all that apply.','Which of the following are named, valid sources of agents that can participate in Multi-Agent Orchestration within watsonx Orchestrate?','MR','multi_select','["Agents from third-party platforms (e.g., via A2A or an OpenAI-compatible chat-completions endpoint)","Agents from watsonx.ai","WXO assistants used as Collaborator Agents","External A2A agents configured using the ADK","Spreadsheet macros imported directly as agents with no wrapping"]',ARRAY['A','B','C','D'],'Valid sources are third-party platform agents, watsonx.ai agents, WXO assistants as collaborators, and external A2A agents via ADK. Spreadsheet macros are not documented.',2,'Agent and Assistant Integration',7,10,'advanced',true),

-- Q11
(gen_random_uuid(),'A developer exported a flow from the embedded Langflow visual editor and now wants it usable as a callable capability inside a native WXO agent. Which sequence is correct?','A developer exported a Langflow flow and wants it as a callable capability inside a WXO agent. Which sequence is correct?','MC','mcq','["The exported flow becomes usable automatically the moment it is saved in Langflow; no further configuration step exists","The flow must be configured and integrated using the ADK (Start ADK) so it is wired into a WXO agent as a tool; simply exporting the JSON is not sufficient","The flow must first be rewritten as a native Agentic Workflow, since Langflow output cannot be reused as a tool","The flow must be disabled from the AI Gateway before it can be attached to any agent"]',ARRAY['B'],'Langflow tools are configured and integrated via ADK (Start ADK) to be wired into a WXO agent — the visual export alone is not sufficient.',2,'Agent and Assistant Integration',7,11,'intermediate',true),

-- Q12
(gen_random_uuid(),'A best-practices document states that deeply nested collaborator hierarchies are discouraged. Which explanation correctly captures WHY?','A best-practices document states that deeply nested collaborator hierarchies are discouraged. Which explanation correctly captures WHY?','MC','mcq','["Because WXO technically forbids more than one layer of nesting and will reject the configuration outright","Because each additional delegation layer compounds latency and reasoning complexity, not because deep nesting is technically blocked or a hard security violation","Because nesting is a documented security violation that automatically fails compliance audits","Because nesting eliminates the need for Connections, which then breaks every downstream tool call"]',ARRAY['B'],'Deep nesting is discouraged because each additional delegation layer adds latency and reasoning overhead — a design/performance concern, not a hard technical restriction.',2,'Agent and Assistant Integration',7,12,'intermediate',true),

-- Q13
(gen_random_uuid(),'An enterprise already has a mature, production watsonx Assistant flow that handles a narrow, well-defined FAQ task extremely reliably. A new architecture calls for a reasoning Agent to handle broader, ambiguous requests but should hand off to the existing Assistant whenever the request matches the FAQ scope. Which statement is correct?','An enterprise has a production watsonx Assistant for FAQ tasks. A new reasoning Agent should hand off to it for the FAQ scope. Which statement is correct?','MC','mcq','["This is impossible; an existing Assistant flow can never participate in agent-based orchestration once built","The existing Assistant flow can be exposed to the orchestrating Agent as a collaborator for that well-defined sub-task, or wrapped and presented in agent form — it does not need to be rebuilt from scratch","The Assistant must first be reduced to a Knowledge Base document before it can be referenced by any Agent","Only External Agents on other vendor platforms can be used as collaborators; native WXO Assistants are excluded"]',ARRAY['B'],'AI assistants can be reused as collaborators for well-defined sub-tasks, or wrapped and presented to the orchestration layer in agent form, without being rebuilt from scratch.',2,'Agent and Assistant Integration',7,13,'intermediate',true),

-- Q14
(gen_random_uuid(),'Which pairing correctly matches an agent-related construct with its defining characteristic, while the other three pairings each swap in a trait that actually belongs to a DIFFERENT construct?','Which pairing correctly matches an agent-related construct with its defining characteristic?','MC','mcq','["External Agent — a WXO-native asset invoked internally by a parent agent for a subtask","Assistant — an autonomous reasoner that dynamically plans and selects tools via an LLM with no fixed flow","Collaborator Agent — any agent, native or external, that a parent/orchestrator agent is permitted to delegate a subtask to (a delegation relationship, not a hosting location)","Agent — a rule-bound, designer-authored conversational flow with no autonomous reasoning"]',ARRAY['C'],'Collaborator Agent describes a delegation relationship and can include either native or external agents. Options A, B, and D each describe traits that belong to a different construct.',2,'Agent and Assistant Integration',7,14,'advanced',true),

-- Q15
(gen_random_uuid(),'A team wants to integrate a vendor agent that only exposes an OpenAI-compatible chat-completions endpoint, with no A2A support. Which integration path is appropriate?','A team wants to integrate a vendor agent with only an OpenAI-compatible chat-completions endpoint, no A2A support. Which integration path is appropriate?','MC','mcq','["It cannot be integrated at all, because A2A is the only supported protocol for third-party agents","Third-party platforms can be integrated via A2A OR via an OpenAI-compatible chat-completions endpoint, so the vendor''s endpoint is a valid integration path even without A2A support","It can only be integrated by rebuilding the vendor''s entire agent natively inside WXO using the ADK","It can only be integrated by first converting it into a Knowledge Base document"]',ARRAY['B'],'Named integration paths for third-party platform agents include A2A and an OpenAI-compatible chat-completions endpoint. Lacking A2A support does not block integration.',2,'Agent and Assistant Integration',7,15,'intermediate',true),

-- Q16
(gen_random_uuid(),'In the Agent Catalog, a junior admin insists that any authenticated user can view or edit any agent because "the Catalog is a shared repository by design." Which correction is accurate?','In the Agent Catalog, a junior admin insists any authenticated user can view or edit any agent. Which correction is accurate?','MC','mcq','["The admin is correct; the Catalog intentionally has no access restrictions of any kind","RBAC and lifecycle governance apply to the Catalog, restricting view/edit access by team/role rather than granting universal edit rights to any authenticated user","Access is restricted only by an agent''s file size, not by role or team","Access is restricted only in the Prod environment; Dev and Test Catalog entries are fully open to all users"]',ARRAY['B'],'RBAC and lifecycle governance control who can view or edit Catalog agents (often team-scoped), contradicting the claim of universal, unrestricted access.',2,'Agent and Assistant Integration',7,16,'intermediate',true),

-- Q17
(gen_random_uuid(),'Why does accuracy tend to degrade when a single agent is given too many tools, and what is the recommended remedy?','Why does accuracy tend to degrade when a single agent is given too many tools, and what is the recommended remedy?','MC','mcq','["Accuracy degrades because tool-selection reasoning becomes harder to disambiguate as the tool list grows; the recommended remedy is narrowly scoped agents (roughly a ~10-tool ceiling) composed together via collaborators","Accuracy degrades because each additional tool consumes a fixed RBAC license seat; the remedy is purchasing more seats","Accuracy degrades because tools are billed per call; the remedy is switching every tool to a Knowledge Base instead","Accuracy degrades only in the Dev environment; the remedy is testing exclusively in Prod"]',ARRAY['A'],'Accuracy tends to degrade past roughly ten tools per agent because tool-selection reasoning becomes harder; the documented remedy is narrow scoping composed via collaborators.',2,'Agent and Assistant Integration',7,17,'advanced',true),

-- Q18
(gen_random_uuid(),'A supervisor agent must decide, at runtime, which of five collaborator agents should handle an incoming request. Which factor primarily drives that routing decision?','A supervisor agent must decide which of five collaborator agents should handle an incoming request. Which factor primarily drives that routing decision?','MC','mcq','["Primary driver: the clarity and specificity of each collaborator''s metadata description field, which the LLM uses to reason about routing; incorrect assumption: the order in which the collaborators were created","Primary driver: each collaborator''s file size; incorrect assumption: the collaborator''s description field, which is cosmetic only","Primary driver: alphabetical order of collaborator names; incorrect assumption: the description field","Primary driver: which collaborator was most recently edited; incorrect assumption: description clarity"]',ARRAY['A'],'The clarity of a collaborator''s description field is what the LLM uses to decide when to route to it. Creation order, file size, alphabetical order, and recency of edits are not the documented routing drivers.',2,'Agent and Assistant Integration',7,18,'advanced',true),

-- Q19
(gen_random_uuid(),'Which statement correctly distinguishes Langflow-based tool integration from a native Agentic Workflow built in WXO''s Flow Builder?','Which statement correctly distinguishes Langflow-based tool integration from a native Agentic Workflow built in WXO''s Flow Builder?','MC','mcq','["Langflow tools and Agentic Workflows are functionally and architecturally identical; the only difference is the product name shown in the UI","Langflow provides a visual, node-based low-code orchestration approach that is imported/configured via the ADK as a tool, while Agentic Workflows are defined through WXO''s native flow-building constructs (trigger → actions → decision points → outcomes) directly in the platform","Agentic Workflows can only be built visually in Langflow; there is no native WXO flow-building capability","Langflow tools cannot include any branching logic, while Agentic Workflows can only run generative prompt steps"]',ARRAY['B'],'Langflow is a visual/node-based low-code option integrated as a tool via ADK; Agentic Workflows are WXO''s own native flow-building construct following trigger→actions→decision points→outcomes.',2,'Agent and Assistant Integration',7,19,'intermediate',true),

-- Q20
(gen_random_uuid(),'Which of the following correctly describe HOW a third-party or external agent can be brought into watsonx Orchestrate? Select all valid integration mechanisms.','Which of the following correctly describe HOW a third-party or external agent can be brought into watsonx Orchestrate? Select all valid integration mechanisms.','MR','multi_select','["Configuring it as an External A2A agent using the ADK","Connecting via an OpenAI-compatible chat-completions endpoint","Wrapping an existing WXO Assistant flow and presenting it to the orchestration layer in agent form","Uploading the vendor''s compiled binary directly into a Knowledge Base as a searchable document"]',ARRAY['A','B','C'],'A2A configuration via ADK, OpenAI-compatible chat-completions endpoints, and wrapping an existing Assistant flow as an agent are all documented mechanisms. Uploading a compiled binary into a Knowledge Base is not.',2,'Agent and Assistant Integration',7,20,'advanced',true),

-- Q21
(gen_random_uuid(),'Section 2 (Agent and Assistant Integration) is the heaviest-weighted domain on the exam. A candidate wrongly recalls it as tied with Section 4 at 18%. What is the correct weighting relationship?','Section 2 is the heaviest-weighted domain. A candidate wrongly recalls it as tied with Section 4 at 18%. What is the correct weighting relationship?','MC','mcq','["Section 2 is approximately 20%, making it heavier than Section 4''s approximately 18% — they are not tied","Section 2 and Section 4 are exactly tied at 18% each","Section 2 is approximately 14%, lighter than Section 4''s 18%","Section 2 is approximately 25%, more than double Section 4''s weighting"]',ARRAY['A'],'Section 2 accounts for approximately 20% of the exam — the single heaviest section — while Section 4 (Agent Development) is the second-heaviest at approximately 18%.',2,'Agent and Assistant Integration',7,21,'intermediate',true),

-- Q22
(gen_random_uuid(),'A workflow designer wants a sub-task that summarizes an unpredictable, free-text customer complaint into three bullet points before a deterministic routing decision is made. Which flow element is appropriate?','A workflow designer wants to summarize an unpredictable, free-text customer complaint into bullet points before a deterministic routing decision. Which flow element is appropriate?','MC','mcq','["Appropriate: a generative prompt step, since the task benefits from language understanding/generation; wrong choice: a code block, which is meant for deterministic logic","Appropriate: a code block, since summarization is fundamentally a string-manipulation problem; wrong choice: a generative prompt step","Appropriate: a Knowledge Base retrieval, since summarization always requires grounding in stored documents","Appropriate: an AI Gateway model policy, since summarization quality is purely a matter of model routing"]',ARRAY['A'],'Generative prompt steps handle language-centric sub-tasks such as summarization or free-text classification; code blocks are for deterministic logic.',3,'Workflow and Orchestration Design',7,22,'intermediate',true),

-- Q23
(gen_random_uuid(),'During ADK import of an MCP tool, a developer assumes the ADK fully executes every possible tool call against live systems to ''prove'' the tool works end-to-end before it can be attached to an agent. Why is this assumption incorrect?','During ADK import of an MCP tool, a developer assumes the ADK fully executes every possible tool call against live systems. Why is this assumption incorrect?','MC','mcq','["ADK import validates the tool''s schema, not full runtime execution against every possible call — full behavioral verification is typically done separately with MCP Inspector before import","The ADK never validates anything at all during import; validation is entirely manual","The ADK executes every call, but only against a randomly selected 10% sample","The ADK requires the tool to be attached to a live agent in Prod before any validation can occur"]',ARRAY['A'],'ADK import validates the tool''s schema, not full execution. MCP Inspector is the utility used to call each tool directly and confirm its schema/behavior before import.',3,'Workflow and Orchestration Design',7,23,'intermediate',true),

-- Q24
(gen_random_uuid(),'A developer registers a remote MCP server and it repeatedly fails validation. A teammate suggests "maybe the server is just slow — let''s give it two minutes to respond during validation." What is actually true about this constraint?','A developer registers a remote MCP server that repeatedly fails validation. A teammate suggests giving it two minutes to respond. What is actually true?','MC','mcq','["There is no time constraint at all; validation waits indefinitely","Remote MCP tool imports via the ADK are subject to a 30-second response window during schema validation, so a server that takes two minutes would exceed it and fail","The constraint is exactly 5 minutes, so the teammate''s two-minute estimate would actually succeed","The time constraint only applies to local MCP servers, not remote ones"]',ARRAY['B'],'Remote MCP imports are subject to a 30-second response window during validation. A two-minute delay would exceed that window and fail.',3,'Workflow and Orchestration Design',7,24,'advanced',true),

-- Q25
(gen_random_uuid(),'An architect wants to expose a curated, governed subset of tools drawn from three different MCP servers to a set of consuming agents, without registering each of the three servers individually with every agent. Which ContextForge MCP Gateway construct achieves this?','An architect wants to expose a curated, governed subset of tools from three MCP servers without registering each server individually. Which ContextForge MCP Gateway construct achieves this?','MC','mcq','["A ''virtual server,'' which combines tools from multiple MCP servers into a curated, secured subset for consuming agents; commonly confused with a Governance MCP Gateway","A ''virtual model,'' which abstracts the underlying LLM provider — this has nothing to do with combining MCP tool sets","An ''Orchestrate MCP Connect'' object","A Knowledge Base collection, since combining tool sets is functionally identical to combining documents"]',ARRAY['A'],'A ContextForge "virtual server" combines tools from multiple MCP servers under centralized governance as a curated subset. A "virtual model" is an unrelated AI Gateway concept.',3,'Workflow and Orchestration Design',7,25,'advanced',true),

-- Q26
(gen_random_uuid(),'A finance team needs an agent capability for credit checks where auditability, precise calculation, and cross-framework reuse (so other non-WXO agents can also call it) all matter more than free-form generation. Which tool type best fits?','A finance team needs credit check capability with auditability, precise calculation, and cross-framework reuse. Which tool type best fits?','MC','mcq','["An MCP tool is the best fit because it supports structured, auditable, framework-agnostic data exchange; a Langflow tool would be a weaker fit because it is not inherently a cross-framework protocol-level interface reusable outside WXO","A Langflow tool is the best fit because visual flows are inherently more auditable than any code-based tool","A generative prompt step is the best fit because credit checks fundamentally require creative language generation","Neither MCP nor Langflow matters; only the AI Gateway''s model policy determines auditability"]',ARRAY['A'],'MCP tools are well suited to precise, auditable operations reusable across frameworks. Langflow tools are a visual, WXO-integrated orchestration option not best suited for cross-framework, protocol-level auditable reuse.',3,'Workflow and Orchestration Design',7,26,'advanced',true),

-- Q27
(gen_random_uuid(),'Which of the following are explicitly named categories of pre-built domain agents available in the watsonx Orchestrate Agent Catalog? Select all that are named categories.','Which of the following are explicitly named categories of pre-built domain agents available in the watsonx Orchestrate Agent Catalog?','MR','multi_select','["HR agents","Sales agents","Finance/procurement agents","IT/security agents","Meteorological/weather-forecasting agents"]',ARRAY['A','B','C','D'],'HR, Sales, Finance/procurement, and IT/security are the named pre-built domain agent categories. Weather-forecasting agents are not a documented category.',3,'Workflow and Orchestration Design',7,27,'intermediate',true),

-- Q28
(gen_random_uuid(),'A team registers a local MCP server using the ADK CLI. A colleague claims this same syntax is also how you register a REMOTE MCP server reachable over HTTPS. Why is that claim misleading?','A team registers a local MCP server using ADK CLI. A colleague claims the same syntax works for registering remote MCP servers. Why is that claim misleading?','MC','mcq','["It is not misleading; local and remote registration always use an identical command with no distinguishing parameters","Local MCP servers are registered by launching a local command; remote MCP servers are registered with parameters describing how to reach the server over the network, so the same local-command syntax does not directly apply","Remote MCP servers cannot be registered at all through the ADK CLI under any circumstances","Local MCP registration requires the --with-langflow flag, which the colleague''s command is missing"]',ARRAY['B'],'Registering a remote MCP server requires parameters that specify how to reach it over the network, distinct from the local-process command pattern used for local servers.',3,'Workflow and Orchestration Design',7,28,'intermediate',true),

-- Q29
(gen_random_uuid(),'In the flow outline "Trigger → sequence of actions → decision points → outcomes," a designer inserts a decision point BEFORE any actions have run. What is the flaw in that reasoning?','In the standard flow outline, a designer inserts a decision point BEFORE any actions have run. What is the flaw in that reasoning?','MC','mcq','["There is no flaw; decision points can occur in any order with no effect on the outcome","The standard pattern places decision points after a sequence of actions has produced information to decide on; evaluating a decision before any actions have executed means there is no new information yet to base that decision on","Decision points are not a real construct in watsonx Orchestrate workflows","Triggers must always occur after outcomes, so the designer''s ordering is actually the correct one"]',ARRAY['B'],'The documented pattern is trigger → actions → decision points → outcomes because decision points typically evaluate the results actions have produced; moving a decision point before any actions undermines that logic.',3,'Workflow and Orchestration Design',7,29,'intermediate',true),

-- Q30
(gen_random_uuid(),'An agent needs to answer "What is our current parental-leave policy?" using a static, board-approved internal PDF that rarely changes, and also needs to "submit a vacation request" which updates a live HR system record. Which design correctly separates these two needs?','An agent needs to answer a policy question from a static PDF and also submit a vacation request to a live HR system. Which design correctly separates these two needs?','MC','mcq','["Both should be handled entirely by LLM reasoning, since the model can approximate both facts and system updates","The policy question should retrieve from a Knowledge Base (grounded in the verified document); the vacation-request submission should call a tool/connection (since it is a live action with a side effect)","Both should be handled by the same Knowledge Base, since knowledge bases can also submit live system updates","Both should be handled by a single generative prompt step with no tool or Knowledge Base involved"]',ARRAY['B'],'Knowledge Base retrieval fits static, verified reference content; tool/connection calls fit live actions with side effects such as submitting a request.',4,'Agent Development',7,30,'intermediate',true),

-- Q31
(gen_random_uuid(),'A designer writes an agent''s purpose statement as only: "This agent helps with HR." A reviewer flags it as incomplete per the recommended design guidance. What is missing?','A designer writes an agent''s purpose statement as only "This agent helps with HR." A reviewer flags it as incomplete. What is missing?','MC','mcq','["Nothing; a one-line purpose statement is the documented best practice and needs no further detail","The statement should also explicitly capture what the agent does NOT do, not just a broad description of what it does — scope boundaries matter as much as the stated purpose","The statement should instead list every tool the agent will ever use, since tools — not purpose — are what reviewers check first","The statement should be replaced entirely with the agent''s model name, since purpose is inferred automatically from model selection"]',ARRAY['B'],'A precise purpose statement should define what the agent does, and just as importantly, what it does NOT do — explicit non-goals are part of the documented guidance.',4,'Agent Development',7,31,'intermediate',true),

-- Q32
(gen_random_uuid(),'A junior developer claims that "agent evaluation only checks whether the final answer text is correct, since that''s ultimately what the end user sees." Why does this understate what agent evaluation actually checks?','A junior developer claims agent evaluation only checks final answer text. Why does this understate what agent evaluation actually checks?','MC','mcq','["The claim is fully accurate; evaluation exclusively scores final-answer text and nothing else","Evaluation also checks the reasoning trajectory — including which tools were called and in what order — not just the final answer, because a correct-looking answer reached via the wrong tool calls can still indicate a flawed or unreliable agent","Evaluation only checks response latency, not answer content or tool calls at all","Evaluation is performed exclusively in production via observability, never before release"]',ARRAY['B'],'Agent evaluation checks the reasoning trajectory (including tool-call sequence), not merely the final answer text, since an agent could reach a superficially correct answer through an unreliable or incorrect path.',4,'Agent Development',7,32,'advanced',true),

-- Q33
(gen_random_uuid(),'Comparing "recording" versus "generating" user stories for evaluation datasets, which correctly distinguishes the two?','Comparing "recording" versus "generating" user stories for evaluation datasets, which correctly distinguishes the two?','MC','mcq','["Recording captures real observed user interactions/transcripts as evaluation cases; generating synthesizes new representative (and adversarial) test cases programmatically — the reverse framing where ''generating'' means manually transcribing live calls is incorrect","Recording and generating are identical processes with different names and produce interchangeable results","Recording always happens in Prod only; generating always happens in Dev only","Generating requires a live customer on the phone, while recording is done entirely offline with synthetic data"]',ARRAY['A'],'Recording captures real, observed interactions as evaluation data; generating synthesizes new test cases (including adversarial ones) programmatically.',4,'Agent Development',7,33,'intermediate',true),

-- Q34
(gen_random_uuid(),'A security reviewer wants to test an agent for vulnerabilities. Which of the following is the PRIMARY purpose of that testing?','A security reviewer wants to test an agent for vulnerabilities. Which of the following is the PRIMARY purpose of that testing?','MC','mcq','["Primarily to confirm the agent''s response time meets an SLA, since speed is the main vulnerability concern","Primarily to identify weaknesses such as susceptibility to prompt injection, over-broad tool access, or data leakage before the agent is exposed to real users and untrusted input","Primarily to verify the agent''s UI color scheme meets accessibility contrast ratios","Primarily to confirm billing accuracy for API calls made during testing"]',ARRAY['B'],'Vulnerability testing focuses on security weaknesses (prompt injection susceptibility, excessive tool access, data leakage) before production exposure.',4,'Agent Development',7,34,'advanced',true),

-- Q35
(gen_random_uuid(),'Which of the following are recognized security risks associated with prompts in AI agents? Select all that are documented risks.','Which of the following are recognized security risks associated with prompts in AI agents?','MR','multi_select','["Prompt injection attempting to override an agent''s system instructions","An agent with broad tool access processing untrusted user input, increasing the blast radius of a successful injection","Data leakage of sensitive information through crafted prompts","Slow page-load times for the chat widget''s CSS assets"]',ARRAY['A','B','C'],'Prompt injection, broad tool access combined with untrusted input, and data leakage via crafted prompts are all documented prompt-related security risks. Slow CSS load times are a UI performance issue.',4,'Agent Development',7,35,'advanced',true),

-- Q36
(gen_random_uuid(),'When breaking down a business workflow into automation steps, a designer maps every single step to "an agent" regardless of what the step actually does. Why is this flawed?','When breaking down a workflow into automation steps, a designer maps every step to "an agent" regardless of what the step does. Why is this flawed per documented breakdown guidance?','MC','mcq','["It is not flawed; every step in every workflow should always be mapped to an agent for maximum flexibility","Each step should be mapped to whichever of an agent, a tool, a connection, or a flow branch actually fits its nature — routing every step through an agent regardless of fit can add unnecessary reasoning overhead and cost where a deterministic tool or flow branch would suffice","Steps should only ever be mapped to Knowledge Bases, never to agents, tools, connections, or flow branches","Steps should be mapped based solely on alphabetical order of their names"]',ARRAY['B'],'Steps are mapped to whichever construct fits — an agent, a tool, a connection, or a flow branch — not uniformly to agents.',4,'Agent Development',7,36,'intermediate',true),

-- Q37
(gen_random_uuid(),'A design calls for an agent to draft five alternative marketing taglines with no need for live data, external system calls, or reference documents. Which capability should the agent primarily rely on?','A design calls for an agent to draft five alternative marketing taglines with no need for live data or reference documents. Which capability should the agent primarily rely on?','MC','mcq','["Primarily LLM reasoning alone, since the task is open-ended creative generation with no need for grounding in verified documents or live system data — attaching a Knowledge Base or tool would add unnecessary complexity","Primarily a Knowledge Base, since all creative writing tasks must be grounded in existing documents by definition","Primarily a tool with a live side effect, since taglines should be submitted directly into a production marketing system before being drafted","Primarily an MCP tool, since cross-framework interoperability is essential for tagline brainstorming"]',ARRAY['A'],'Creative brainstorming with no need for precise data, execution, or documented grounding suits LLM reasoning alone; attaching a Knowledge Base or tool adds unneeded complexity.',4,'Agent Development',7,37,'intermediate',true),

-- Q38
(gen_random_uuid(),'The "evaluate the design for reusability and scalability" guideline is sometimes misread as "build one large, all-purpose agent so nothing needs to be rebuilt later." What does this guideline actually encourage designers to avoid?','The guideline "evaluate the design for reusability and scalability" is sometimes misread as building one large, all-purpose agent. What does this guideline actually encourage designers to avoid?','MC','mcq','["It encourages avoiding narrowly scoped, single-purpose agents in favor of one broad generalist agent","It encourages avoiding an overloaded generalist agent with an unmanageable tool list, favoring narrowly scoped agents composed via collaborators for reuse across multiple orchestrations","It encourages avoiding the use of collaborators entirely, since collaborators reduce reusability","It encourages avoiding any testing before Prod, since testing slows down reusability"]',ARRAY['B'],'The guideline encourages avoiding an overloaded, single generalist agent in favor of narrowly scoped agents composed via collaborators.',4,'Agent Development',7,38,'advanced',true),

-- Q39
(gen_random_uuid(),'An agent''s guidelines state only "be helpful and friendly." A compliance reviewer says this is insufficient as a behavioral profile. What specifically should the guidelines also address?','An agent''s guidelines state only "be helpful and friendly." A compliance reviewer says this is insufficient. What specifically should the guidelines also address?','MC','mcq','["Nothing further is required; tone alone satisfies governance requirements for a behavioral profile","How the agent should behave when uncertain, what it must never disclose or do, and which situations require human approval — treating the behavioral profile as a compliance control, not just a tone guideline","Only the agent''s preferred emoji usage needs to be specified further","Only the marketing team''s brand voice guidelines need to be added, with no compliance-related content"]',ARRAY['B'],'Guidelines should explicitly cover uncertainty handling, disclosure/action boundaries, and human-approval triggers — treating the behavioral profile as a compliance control.',4,'Agent Development',7,39,'advanced',true),

-- Q40
(gen_random_uuid(),'Comparing evaluation and observability, a developer states: "since observability watches the agent continuously in production, there''s no need to run pre-release evaluation against known scenarios." What is wrong with this reasoning?','A developer states that since observability watches the agent continuously in production, pre-release evaluation is not needed. What is wrong with this reasoning?','MC','mcq','["Nothing is wrong; observability alone is sufficient and pre-release evaluation is redundant","Evaluation is a build-time/pre-release check against known (and adversarial) scenarios, while observability monitors real production behavior continuously; skipping evaluation means regressions are only caught after real users are already affected","Observability cannot run at all unless evaluation is skipped first","Evaluation and observability are the same process performed at two different times of day with no functional difference"]',ARRAY['B'],'Evaluation and observability are complementary: evaluation is pre-release testing against known/adversarial scenarios; observability is continuous production monitoring.',4,'Agent Development',7,40,'advanced',true),

-- Q41
(gen_random_uuid(),'An architect configures two agents to reference an LLM by a logical name rather than a specific provider endpoint. When the primary provider suffers a regional outage, requests are automatically rerouted to a backup provider with no change to either agent''s definition. Which AI Gateway concept explains this?','Two agents reference an LLM by a logical name. When the primary provider has an outage, requests reroute to a backup with no change to either agent''s definition. Which AI Gateway concept explains this?','MC','mcq','["A ''model policy typo,'' which coincidentally happened to still resolve correctly","A ''virtual model,'' which abstracts the underlying provider from the agent definition, so the Gateway can resolve the logical reference to a different provider/endpoint at runtime without touching the agent''s configuration","RBAC, which has no bearing on model routing and only governs user permissions","A Knowledge Base embedding index, which is unrelated to LLM provider routing"]',ARRAY['B'],'A virtual model lets an agent reference a model logically; the Gateway resolves that reference to the actual provider/endpoint at runtime, enabling failover without changing the agent definition.',5,'Model Management',7,41,'intermediate',true),

-- Q42
(gen_random_uuid(),'Two model-policy behaviors are being compared: one reroutes traffic to a backup model only when the primary is unavailable or rate-limited; the other continuously distributes ongoing requests across multiple equivalent models even when all are healthy. Which term applies to each, respectively?','Two model-policy behaviors: one reroutes to backup only when primary is unavailable; the other distributes requests across multiple healthy models. Which term applies to each, respectively?','MC','mcq','["Failover; load balancing","Load balancing; failover","Both are called ''failover''; there is no separate term for the second behavior","Both are called ''load balancing''; there is no separate term for the first behavior"]',ARRAY['A'],'Failover routes to a backup model specifically when the primary is unavailable/rate-limited; load balancing distributes ongoing traffic across multiple equivalent healthy models.',5,'Model Management',7,42,'intermediate',true),

-- Q43
(gen_random_uuid(),'A team believes that because "popular" third-party LLMs are trending in the industry press, popularity alone is sufficient justification for selecting a model for a specific agent task. Why is this reasoning explicitly discouraged?','A team believes popularity alone is sufficient justification for selecting a model for a specific agent task. Why is this reasoning explicitly discouraged?','MC','mcq','["Popularity alone, without weighing cost, accuracy, and latency tradeoffs for the specific task, is explicitly called out as an invalid sole selection criterion","Popularity is actually the single most important and sufficient criterion, more important than cost, accuracy, or latency combined","Model selection is irrelevant because the AI Gateway makes all models perform identically regardless of choice","Cost, accuracy, and latency are themselves invalid criteria; only popularity should be used"]',ARRAY['A'],'Popularity alone, ignoring cost/accuracy/latency tradeoffs, is explicitly called out as NOT a valid sole criterion.',5,'Model Management',7,43,'intermediate',true),

-- Q44
(gen_random_uuid(),'An admin registers a new AI Gateway instance for an on-premises deployment and configures three chat models but no embedding model, then reports that knowledge-base semantic search is failing. What is the most likely root cause?','An admin configures three chat models but no embedding model on a new AI Gateway instance. Knowledge-base semantic search is failing. What is the most likely root cause?','MC','mcq','["On-premises deployments do not support the AI Gateway at all, so this failure is expected regardless of configuration","At least one default embedding model is required per AI Gateway instance (alongside a default LLM) for semantic search to function; registering only chat/LLM models without an embedding model would leave that requirement unmet","Knowledge-base semantic search never depends on the AI Gateway; the failure must be unrelated to model registration","The failure is caused by RBAC misconfiguration, since embedding models are unrelated to the AI Gateway"]',ARRAY['B'],'At least one default embedding model is required per AI Gateway instance; omitting the embedding model would break embedding-dependent functionality like KB semantic search.',5,'Model Management',7,44,'advanced',true),

-- Q45
(gen_random_uuid(),'A governance dashboard shows rising cost and degrading latency for a particular agent''s default model over several weeks. A stakeholder asks whether this data is "just informational, with no real operational consequence." What is the correct relationship between such dashboards and model policies?','A governance dashboard shows rising cost and degrading latency. A stakeholder asks if this data is "just informational." What is the correct relationship between such dashboards and model policies?','MC','mcq','["The data is purely informational; governance dashboards have no connection to model policy decisions","Usage, cost, and performance visibility surfaced through governance dashboards often informs when a new or adjusted model policy (e.g., switching the default model, adjusting failover) is warranted — it is not merely informational with no operational consequence","Governance dashboards automatically rewrite model policies with no human review whenever a threshold is crossed","Governance dashboards only display cost, never latency or usage, so this scenario could not occur"]',ARRAY['B'],'Dashboard insights (usage, cost, performance) inform when/how model policies should change — they are operationally significant, not merely informational.',5,'Model Management',7,45,'intermediate',true),

-- Q46
(gen_random_uuid(),'An organization validates a model policy thoroughly in Dev and now wants Prod to use the identical, already-validated configuration rather than a manually re-created approximation. What is the documented reason to import the existing policy rather than recreate it by hand?','An organization wants Prod to use the exact same model policy validated in Dev. What is the documented reason to import rather than recreate by hand?','MC','mcq','["Manual recreation in each environment is always faster and is the preferred, documented approach","Importing ensures consistent governance and guardrails as the policy is promoted across environments, avoiding drift or human error introduced by manually re-typing the configuration","Importing bypasses all authentication checks, which is the primary benefit","Policies cannot be reused across environments under any circumstances; each must be built independently"]',ARRAY['B'],'Importing an existing, validated model policy preserves consistent governance/guardrails across environments and avoids the drift or error risk of manual recreation.',5,'Model Management',7,46,'intermediate',true),

-- Q47
(gen_random_uuid(),'For a reasoning-heavy, multi-step planning task, a developer defaults to the smallest, cheapest available model "because latency matters most for user experience." What tradeoff is this decision most likely to mishandle?','For a reasoning-heavy, multi-step planning task, a developer defaults to the smallest, cheapest model for latency. What tradeoff is this decision most likely to mishandle?','MC','mcq','["Nothing; smaller models are always superior for reasoning-heavy planning tasks regardless of accuracy needs","Larger, more capable models generally benefit reasoning-heavy planning tasks; defaulting to the smallest/cheapest model purely for latency risks under-serving accuracy on exactly the task type where it matters most","Latency is irrelevant to model selection in all cases, so the developer''s reasoning is moot either way","Cost is the only factor that should ever be considered, making this the correct decision regardless of task type"]',ARRAY['B'],'Reasoning-heavy planning tasks generally benefit from larger, more capable models; defaulting to the smallest/cheapest model purely to optimize latency risks sacrificing accuracy on the task type where it matters most.',5,'Model Management',7,47,'advanced',true),

-- Q48
(gen_random_uuid(),'Which of the following are explicitly named features/capabilities of the AI Gateway? Select all that are documented features.','Which of the following are explicitly named features/capabilities of the AI Gateway? Select all that are documented features.','MR','multi_select','["Registration and routing of multiple LLM/embedding providers behind a common interface","Routing policies covering default model assignment, failover, and load balancing","Centralized credential management that can integrate with a secrets manager","Automatic generation of marketing copy for newly registered models"]',ARRAY['A','B','C'],'Registration/routing across providers, routing policies (default/failover/load balancing), and centralized credential management (integrating with a secrets manager) are named AI Gateway features.',5,'Model Management',7,48,'advanced',true),

-- Q49
(gen_random_uuid(),'A developer configures programmatic ADK/API access for a CI/CD pipeline using the same shared human password an engineer uses to log into the console interactively. A security reviewer flags this. What is the correct approach?','A developer uses a shared human password for programmatic ADK/API access in a CI/CD pipeline. A security reviewer flags this. What is the correct approach?','MC','mcq','["Programmatic ADK/API access should use API keys/tokens, distinct from the federated identity/IAM sign-in mechanism used for interactive human console access — reusing a shared human password is not the documented pattern","There is no distinction; the same interactive human password is the documented and only supported mechanism for both console login and programmatic API access","Programmatic access should always use biometric fingerprint scanners, since API keys are not supported","Programmatic access requires no authentication at all, by design, so the reviewer''s concern is unfounded"]',ARRAY['A'],'API keys/tokens are the documented mechanism for programmatic ADK/API access, distinct from federated identity/IAM used for interactive user sign-in.',6,'Security, Compliance, and Observability',7,49,'advanced',true),

-- Q50
(gen_random_uuid(),'An operator sees a spike in "trajectory deviations" on the observability dashboard for a specific agent, alongside normal token-usage numbers. What does this signal most directly suggest?','An operator sees a spike in "trajectory deviations" on the observability dashboard, alongside normal token-usage numbers. What does this signal most directly suggest?','MC','mcq','["It most directly suggests the agent is calling the wrong tool or skipping an expected step (a reasoning-path problem), not that raw token consumption itself is the underlying issue, since token usage is reported as normal","It most directly suggests a UI color-contrast accessibility failure unrelated to agent reasoning","It most directly suggests the environment naming convention was violated during setup","It most directly suggests billing has failed for that agent''s API calls"]',ARRAY['A'],'Trajectory deviations flag cases where an agent calls the wrong tool or skips an expected step — a reasoning-path issue distinct from token usage, UI styling, naming conventions, or billing.',6,'Security, Compliance, and Observability',7,50,'advanced',true),

-- Q51
(gen_random_uuid(),'A compliance officer asks whether Security and Privacy by Design (SPbD) means adding redaction and access controls only after an incident occurs. How should this be corrected?','A compliance officer asks whether Security and Privacy by Design means adding controls only after an incident occurs. How should this be corrected?','MC','mcq','["SPbD does mean exactly that: controls are added reactively only after a breach is detected","SPbD means building privacy and security controls into an agent from the outset — e.g., input/output plug-ins to redact sensitive data, least-privilege connections, and access-controlled knowledge bases — proactively rather than as a reactive, post-incident remediation","SPbD is purely a marketing term with no technical implementation","SPbD applies only to External Agents, never to native WXO agents or Knowledge Bases"]',ARRAY['B'],'SPbD embeds privacy/security controls proactively from the outset (redaction plug-ins, least-privilege connections, access-controlled KBs) — the opposite of a reactive, post-incident-only approach.',6,'Security, Compliance, and Observability',7,51,'intermediate',true),

-- Q52
(gen_random_uuid(),'Which of the following are documented elements administrators verify using IBM''s published security checklist for authentication, authorization, and audit compliance? Select all that apply.','Which of the following are documented elements administrators verify using IBM''s published security checklist?','MR','multi_select','["Identity mechanisms are configured correctly","RBAC roles are assigned appropriately","Audit logging is enabled and retained per policy","The chatbot widget uses an approved brand font"]',ARRAY['A','B','C'],'The checklist covers identity configuration, RBAC role assignment, and audit logging/retention — substantive compliance concerns, not cosmetic UI details such as widget fonts.',6,'Security, Compliance, and Observability',7,52,'advanced',true),

-- Q53
(gen_random_uuid(),'An organization enables external logging that forwards activity data to a SIEM, and separately relies on the platform''s built-in dashboards. A stakeholder asks whether enabling external logging makes the built-in dashboards redundant and safe to ignore. What is the correct relationship?','An organization enables external logging to a SIEM and also uses built-in dashboards. Are the built-in dashboards now redundant?','MC','mcq','["External logging replaces built-in dashboards entirely; once SIEM forwarding is enabled, native dashboards no longer serve any purpose","External logging forwards activity data to systems like a SIEM for centralized enterprise monitoring, while built-in dashboards surface metrics natively in the platform UI — they are complementary, not mutually exclusive","Built-in dashboards require external logging to be enabled before they will display any data at all","Enabling external logging automatically disables the built-in dashboards by design"]',ARRAY['B'],'External logging (to a SIEM) and native built-in dashboards serve complementary purposes — neither replaces or requires the other.',6,'Security, Compliance, and Observability',7,53,'intermediate',true),

-- Q54
(gen_random_uuid(),'A team integrates watsonx Orchestrate with Langfuse and assumes this replaces the need for the ADK''s own evaluation framework entirely. What is the more accurate characterization of Langfuse''s role?','A team integrates watsonx Orchestrate with Langfuse and assumes this replaces the ADK''s evaluation framework. What is the more accurate characterization of Langfuse''s role?','MC','mcq','["Langfuse fully replaces the ADK Evaluation Framework and pre-release testing becomes unnecessary once it is integrated","Langfuse''s native ADK integration provides visibility into prompts, intermediate reasoning, tool calls, and outputs — primarily an observability capability for understanding production LLM behavior, not a wholesale replacement for pre-release evaluation","Langfuse only works for billing reconciliation and has no connection to observability at all","Langfuse is unrelated to ADK integration and can only be used as a standalone product"]',ARRAY['B'],'Langfuse''s ADK integration gives observability into prompts/reasoning/tool calls/outputs — complementary to, not a replacement for, the pre-release ADK Evaluation Framework.',6,'Security, Compliance, and Observability',7,54,'advanced',true),

-- Q55
(gen_random_uuid(),'A regulated financial-services customer needs to keep certain workflow data within a specific jurisdiction while still benefiting from governed model use. Which combination of platform capabilities most directly supports this requirement?','A regulated financial-services customer needs to keep workflow data within a specific jurisdiction. Which combination of platform capabilities most directly supports this requirement?','MC','mcq','["RBAC alone is sufficient; no other capability is relevant to data residency","A combination of RBAC, encrypted/managed credentials, audit logging, and hybrid/on-prem deployment options (e.g., via Software Hub) together let regulated organizations keep data within required jurisdictional or infrastructure boundaries — no single one of these alone is described as sufficient","Only the AI Gateway''s routing policy matters; RBAC and audit logging are irrelevant to data residency","Data residency is not supported by watsonx Orchestrate under any deployment model"]',ARRAY['B'],'Data residency and regulatory alignment rely on a combination of RBAC, credential management, audit logging, and hybrid/on-prem deployment options together — not any single capability in isolation.',6,'Security, Compliance, and Observability',7,55,'advanced',true),

-- Q56
(gen_random_uuid(),'A platform team wants a change validated in Dev to reach Prod only after passing automated tests and receiving explicit human sign-off, with the ability to roll back automatically if a regression is detected post-deployment. Which combination of CI/CD elements addresses this?','A platform team wants automated tests + human sign-off + automatic rollback capability for changes promoted to Prod. Which combination of CI/CD elements addresses this?','MC','mcq','["Automated deployment triggers plus approval gates plus rollback mechanisms together address this; approval gates alone (with no automated testing or rollback mechanism) would be insufficient to catch a regression that only manifests after deployment","Approval gates alone are fully sufficient; automated testing and rollback mechanisms are optional extras","Rollback mechanisms alone are sufficient, since they can always be triggered manually","None of these elements matter, since watsonx Orchestrate deployments cannot fail once they reach Prod"]',ARRAY['A'],'Deployment automation combines triggers, approval gates (human sign-off), and rollback mechanisms together; relying on approval gates alone would not catch a regression that only becomes apparent after deployment.',7,'Deployment, Scaling, Optimization, and Resiliency',7,56,'advanced',true),

-- Q57
(gen_random_uuid(),'A team stores API keys and connection credentials directly inside version-controlled ADK YAML files "because Git already provides access control." Why is this insufficient as a secrets-management practice?','A team stores API keys and credentials inside version-controlled ADK YAML files, claiming Git access control is sufficient. Why is this insufficient?','MC','mcq','["It is sufficient; Git''s access control is a fully adequate substitute for dedicated secrets management","Secrets and credentials should be securely handled (e.g., via a dedicated secrets manager) rather than committed into version-controlled files, since Git history, forks, and broader repository access typically expose committed secrets far more widely than a dedicated secrets manager would","ADK YAML files cannot technically contain credentials at all, so the scenario is impossible","Secrets management is only relevant in Test, never in Dev, Prod, or CI/CD pipelines generally"]',ARRAY['B'],'Pipelines should manage secrets/credentials securely (e.g., via a secrets manager), not commit them into version-controlled configuration files — Git history and broader repo access make committed secrets far more exposed.',7,'Deployment, Scaling, Optimization, and Resiliency',7,57,'advanced',true),

-- Q58
(gen_random_uuid(),'Two engineers debate why ADK-managed agent/tool/connection artifacts are described as fitting "naturally" into standard Git workflows. Which explanation is accurate?','Two engineers debate why ADK-managed artifacts fit "naturally" into standard Git workflows. Which explanation is accurate?','MC','mcq','["Accurate: because ADK artifacts are code-first, version-controllable definitions (YAML/Python) that can be branched, diffed, and reviewed like any other codebase — not because Git itself executes agent logic","Misattributed: Git workflows fit because Git directly executes and hosts running agents in production","Misattributed: it is only because the no-code Agent Builder UI is itself built on top of Git internally","Misattributed: it is because Knowledge Base documents are stored as Git commits rather than in a vector store"]',ARRAY['A'],'ADK artifacts are code-first (YAML/Python), which is precisely why they branch, diff, and review naturally in Git — Git does not execute agent logic, host running agents, or store KB documents as commits.',7,'Deployment, Scaling, Optimization, and Resiliency',7,58,'intermediate',true),

-- Q59
(gen_random_uuid(),'A regulated customer needs to migrate a fully configured, validated Test environment to a new region while preserving agent/tool/connection/knowledge-base configurations exactly. Which capability supports this?','A regulated customer needs to migrate a fully configured Test environment to a new region while preserving all configurations exactly. Which capability supports this?','MC','mcq','["Environment backup, restore, and migration — exporting/importing agent, tool, connection, and knowledge-base configurations and managing environment versioning; manually re-typing every agent definition from memory is the flawed alternative","There is no supported migration capability; every environment must always be rebuilt manually from scratch","Migration is achieved solely by renaming the Dev environment to the target region''s name","Migration requires deleting all existing configurations permanently first"]',ARRAY['A'],'Environment backup/restore/migration supports exporting/importing configurations and environment versioning for reliable migration.',7,'Deployment, Scaling, Optimization, and Resiliency',7,59,'intermediate',true),

-- Q60
(gen_random_uuid(),'A knowledge base ingestion pipeline uploads a batch of updated policy PDFs that silently corrupt several existing chunks'' embeddings, degrading retrieval accuracy platform-wide for that KB. Which capability should have allowed the team to revert to the last known-good state?','A KB ingestion pipeline corrupts existing embeddings. Which capability should have allowed the team to revert to the last known-good state, and why would rebuilding from scratch NOT be the documented remedy?','MC','mcq','["Knowledge base versioning and updates — which tracks document versions and supports snapshot/rollback procedures so a bad ingestion can be reversed; deleting and rebuilding a brand-new KB from scratch discards this versioning/rollback capability rather than using it","RBAC, since permission settings are what should have prevented the corrupted embeddings from ever being generated","The AI Gateway''s failover policy, since embedding corruption is treated identically to an LLM provider outage","There is no way to recover; once ingested, a knowledge base''s embeddings can never be reverted"]',ARRAY['A'],'Knowledge base versioning tracks document versions and supports snapshot/rollback specifically so a bad ingestion can be reversed — rebuilding from scratch discards that safety net.',7,'Deployment, Scaling, Optimization, and Resiliency',7,60,'advanced',true);

-- ═══════════════════════════════════════════════════════════════
-- 4. Index for retake window enforcement
-- ═══════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_quiz_attempts_first_attempt
  ON quiz_attempts (exam_id, student_id, started_at)
  WHERE status IN ('submitted','graded','in_progress','grading','grading_failed');

COMMIT;

