GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pmaas;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pmaas;
GRANT ALL ON SCHEMA public TO pmaas;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO pmaas;
