"""
platform/agentops/report.py — AgentOps weekly review pack HTML renderer

Pure stdlib — no Jinja2 dependency.  Takes the pack dict produced by
review_pack.build_pack() and returns a self-contained UTF-8 HTML string.

Design
------
- Single-column, max 860 px, IBM / i3 palette (#0f62fe accent).
- Six collapsible sections matching the pack sections, numbered 1–6.
- Color-coded RAG status badges (green / amber / red / grey) inline.
- All data inlined as text — no JavaScript, no external assets.
- Footer: "Generated by i3 AgentOps — IBM Bob · <timestamp> · <week>"
"""

from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# Badge / colour helpers
# ---------------------------------------------------------------------------

_DRIFT_COLOUR = {
    "STABLE":     "#6b7280",  # grey
    "IMPROVING":  "#16a34a",  # green
    "DEGRADING":  "#dc2626",  # red
    "NEW":        "#d97706",  # amber
}

_STATUS_COLOUR = {
    "OPEN":       "#d97706",
    "MITIGATED":  "#16a34a",
    "ACCEPTED":   "#6b7280",
    "CLOSED":     "#9ca3af",
}

_OUTCOME_COLOUR = {
    "SUCCESS":  "#16a34a",
    "FAILURE":  "#dc2626",
    "DENIED":   "#b91c1c",
    "PARTIAL":  "#d97706",
    "UNKNOWN":  "#6b7280",
}


def _badge(label: str, colour: str) -> str:
    style = (
        f"display:inline-block;padding:2px 8px;border-radius:4px;"
        f"background:{colour}22;color:{colour};font-size:11px;"
        f"font-weight:600;border:1px solid {colour}44;"
    )
    return f'<span style="{style}">{html.escape(str(label))}</span>'


def _pct_badge(pct: float | None) -> str:
    if pct is None:
        return _badge("N/A", "#6b7280")
    if pct >= 90:
        colour = "#16a34a"
    elif pct >= 70:
        colour = "#d97706"
    else:
        colour = "#dc2626"
    return _badge(f"{pct:.1f}%", colour)


def _budget_badge(pct: float | None) -> str:
    if pct is None:
        return _badge("N/A", "#6b7280")
    if pct >= 90:
        colour = "#dc2626"
    elif pct >= 70:
        colour = "#d97706"
    else:
        colour = "#16a34a"
    return _badge(f"{pct:.1f}%", colour)


def _eval_badge(passing: bool | None) -> str:
    if passing is True:
        return _badge("PASS", "#16a34a")
    if passing is False:
        return _badge("FAIL", "#dc2626")
    return _badge("NO DATA", "#6b7280")


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------

def _section(title: str, body: str, section_id: str) -> str:
    return f"""
<section id="{section_id}" style="margin-bottom:28px;">
  <h2 style="font-size:15px;font-weight:700;color:#1f2937;border-bottom:1px solid #e5e7eb;
             padding-bottom:6px;margin-bottom:12px;">{html.escape(title)}</h2>
  {body}
</section>"""


def _table(headers: list[str], rows: list[list[str]]) -> str:
    th_style = (
        "padding:7px 10px;text-align:left;font-size:12px;font-weight:600;"
        "background:#f3f4f6;color:#374151;border-bottom:1px solid #e5e7eb;"
    )
    td_style = (
        "padding:6px 10px;font-size:12px;color:#374151;"
        "border-bottom:1px solid #f3f4f6;vertical-align:top;"
    )
    ths = "".join(f"<th style='{th_style}'>{h}</th>" for h in headers)
    trs = ""
    for row in rows:
        tds = "".join(f"<td style='{td_style}'>{cell}</td>" for cell in row)
        trs += f"<tr>{tds}</tr>\n"
    return (
        "<div style='overflow-x:auto;'>"
        f"<table style='border-collapse:collapse;width:100%;'>"
        f"<thead><tr>{ths}</tr></thead>"
        f"<tbody>{trs}</tbody>"
        "</table></div>"
    )


def _no_data(msg: str = "No data available for this period.") -> str:
    return (
        f"<p style='color:#6b7280;font-size:12px;font-style:italic;'>"
        f"{html.escape(msg)}</p>"
    )


# ---------------------------------------------------------------------------
# Section 1 — Autonomy rates
# ---------------------------------------------------------------------------

def _render_autonomy(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return _no_data("No decision-log records for the past 7 days.")
    table_rows = []
    for r in rows:
        table_rows.append([
            html.escape(str(r.get("agent_id", ""))),
            html.escape(str(r.get("tenant_id", ""))[:8] + "…"),
            str(r.get("total_decisions", 0)),
            str(r.get("autonomous_successes", 0)),
            str(r.get("human_overrides", 0)),
            _pct_badge(r.get("autonomy_rate_pct")),
        ])
    return _table(
        ["Agent ID", "Tenant", "Total Decisions", "Autonomous", "Human Overrides", "Autonomy Rate"],
        table_rows,
    )


# ---------------------------------------------------------------------------
# Section 2 — Gate latency
# ---------------------------------------------------------------------------

def _render_latency(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return _no_data("No human-approval events recorded in the past 7 days.")
    table_rows = []
    for r in rows:
        avg = r.get("avg_latency_sec")
        p95 = r.get("p95_latency_sec")
        table_rows.append([
            html.escape(str(r.get("agent_id", ""))),
            html.escape(str(r.get("tenant_id", ""))[:8] + "…"),
            str(r.get("approval_count", 0)),
            f"{avg:.1f}s" if avg is not None else "—",
            f"{p95:.1f}s" if p95 is not None else "—",
        ])
    return _table(
        ["Agent ID", "Tenant", "Approvals", "Avg Latency", "P95 Latency"],
        table_rows,
    )


# ---------------------------------------------------------------------------
# Section 3 — Spend vs budget
# ---------------------------------------------------------------------------

def _render_spend(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return _no_data("No billing data for the current month.")
    table_rows = []
    for r in rows:
        table_rows.append([
            html.escape(str(r.get("tenant_name", ""))),
            html.escape(str(r.get("year_month", ""))),
            f"{r.get('tokens_used', 0):,}",
            f"{r.get('token_budget', 0):,}",
            _budget_badge(r.get("budget_utilisation_pct")),
            str(r.get("over_quota_hits", 0)),
            f"{r.get('request_count', 0):,}",
        ])
    return _table(
        ["Tenant", "Month", "Tokens Used", "Budget", "Utilisation", "429 Hits", "Requests"],
        table_rows,
    )


# ---------------------------------------------------------------------------
# Section 4 — Eval trend
# ---------------------------------------------------------------------------

def _render_eval(eval_data: dict[str, Any]) -> str:
    status = eval_data.get("status", "NO_EVIDENCE")
    passing = eval_data.get("passing")
    metrics = eval_data.get("metrics", {})
    model   = eval_data.get("model", "unknown")
    gate    = eval_data.get("gate", "unknown")
    n       = eval_data.get("n_queries")

    def _metric_row(name: str, val: Any, threshold: float | None = None) -> str:
        if val is None:
            badge = _badge("N/A", "#6b7280")
        else:
            fval = float(val)
            if threshold and fval >= threshold:
                badge = _badge(f"{fval:.3f}", "#16a34a")
            elif threshold:
                badge = _badge(f"{fval:.3f}", "#dc2626")
            else:
                badge = _badge(f"{fval:.3f}", "#6b7280")
        return f"<tr><td style='padding:5px 10px;font-size:12px;'>{name}</td><td style='padding:5px 10px;'>{badge}</td></tr>"

    summary = (
        f"<p style='font-size:12px;margin-bottom:8px;'>"
        f"Gate: <strong>{html.escape(gate)}</strong> &nbsp;|&nbsp; "
        f"Model: <strong>{html.escape(model)}</strong> &nbsp;|&nbsp; "
        f"Queries: <strong>{n or 'N/A'}</strong> &nbsp;|&nbsp; "
        f"Status: {_eval_badge(passing)}</p>"
    )
    metric_table = (
        "<table style='border-collapse:collapse;'>"
        + _metric_row("Faithfulness",      metrics.get("faithfulness"),      0.80)
        + _metric_row("Answer Relevancy",  metrics.get("answer_relevancy"),  0.75)
        + _metric_row("Context Precision", metrics.get("context_precision"),  None)
        + "</table>"
    )
    return summary + metric_table


# ---------------------------------------------------------------------------
# Section 5 — Audit anomalies
# ---------------------------------------------------------------------------

def _render_anomalies(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return _no_data(
            "No FAILURE / DENIED / CRITICAL audit events in the past 7 days. ✓"
        )
    table_rows = []
    for r in rows:
        outcome_col = _badge(
            r.get("outcome", ""),
            _OUTCOME_COLOUR.get(r.get("outcome", ""), "#6b7280"),
        )
        tier_col = _badge(
            r.get("risk_tier", ""),
            "#dc2626" if r.get("risk_tier") == "CRITICAL" else "#d97706",
        )
        table_rows.append([
            html.escape(str(r.get("tenant_slug", ""))),
            html.escape(str(r.get("service", ""))),
            html.escape(str(r.get("action", ""))),
            tier_col,
            outcome_col,
            str(r.get("event_count", 0)),
        ])
    return _table(
        ["Tenant", "Service", "Action", "Risk Tier", "Outcome", "Count (7d)"],
        table_rows,
    )


# ---------------------------------------------------------------------------
# Section 6 — Risk register
# ---------------------------------------------------------------------------

def _render_risk_register(items: list[dict[str, Any]]) -> str:
    if not items:
        return _no_data("Risk register is empty.")
    cards = []
    for r in items:
        drift_colour = _DRIFT_COLOUR.get(r["drift"], "#6b7280")
        status_colour = _STATUS_COLOUR.get(r["status"], "#6b7280")
        controls_html = "".join(
            f"<li style='font-size:11px;color:#6b7280;'>{html.escape(c)}</li>"
            for c in r.get("controls", [])
        )
        card = f"""
<div style="border:1px solid #e5e7eb;border-radius:6px;padding:12px 16px;
            margin-bottom:10px;background:#fafafa;">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;flex-wrap:wrap;gap:6px;">
    <div>
      <span style="font-size:11px;font-weight:700;color:#9ca3af;">{html.escape(r['id'])}</span>
      &nbsp;
      <span style="font-size:13px;font-weight:600;color:#111827;">{html.escape(r['title'])}</span>
    </div>
    <div style="display:flex;gap:6px;flex-wrap:wrap;">
      {_badge(r['category'], '#0f62fe')}
      {_badge('L=' + str(r['likelihood']) + ' I=' + str(r['impact']) + ' S=' + str(r['score']), '#374151')}
      {_badge(r['status'], status_colour)}
      {_badge('⬤ ' + r['drift'], drift_colour)}
    </div>
  </div>
  <p style="font-size:12px;color:#6b7280;margin:6px 0 4px 0;">
    <strong>Owner:</strong> {html.escape(r['owner'])} &nbsp;|&nbsp;
    <strong>Reviewed:</strong> {html.escape(r['last_reviewed'])} &nbsp;|&nbsp;
    <strong>Drift note:</strong> {html.escape(r['drift_note'])}
  </p>
  <ul style="margin:4px 0 0 14px;padding:0;">{controls_html}</ul>
</div>"""
        cards.append(card)
    return "".join(cards)


# ---------------------------------------------------------------------------
# Full document builder
# ---------------------------------------------------------------------------

def render_html(pack: dict[str, Any]) -> str:
    """
    Convert the review pack dict into a self-contained HTML document string.
    """
    generated_at = pack.get("generated_at", datetime.now(timezone.utc).isoformat())
    week         = pack.get("week", "W??-????")
    scope_raw    = pack.get("tenant_scope", "all")
    scope        = ", ".join(scope_raw) if isinstance(scope_raw, list) else str(scope_raw)

    s1 = _section(
        "1 · Autonomy Rate per Agent",
        _render_autonomy(pack.get("autonomy_rates", [])),
        "s1",
    )
    s2 = _section(
        "2 · Approval-Gate Latency",
        _render_latency(pack.get("gate_latency", [])),
        "s2",
    )
    s3 = _section(
        "3 · Spend per Tenant vs Budget",
        _render_spend(pack.get("spend_vs_budget", [])),
        "s3",
    )
    s4 = _section(
        "4 · Evaluation-Suite Trend (RAGAS)",
        _render_eval(pack.get("eval_trend", {})),
        "s4",
    )
    s5 = _section(
        "5 · Audit-Trail Anomalies",
        _render_anomalies(pack.get("audit_anomalies", [])),
        "s5",
    )
    s6 = _section(
        "6 · Top-5 Risk Register (with Drift)",
        _render_risk_register(pack.get("risk_register", [])),
        "s6",
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>i3 AgentOps Weekly Review Pack — {html.escape(week)}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  body {{
    font-family: -apple-system, "Segoe UI", system-ui, sans-serif;
    font-size: 14px; line-height: 1.6;
    background: #f3f4f6; color: #1f2937; margin: 0; padding: 24px 16px;
  }}
  .wrapper {{ max-width: 860px; margin: 0 auto; background: #fff;
              border: 1px solid #e5e7eb; border-radius: 8px;
              padding: 28px 32px; }}
  .header-row {{ display: flex; justify-content: space-between;
                 align-items: flex-start; flex-wrap: wrap; gap: 12px;
                 margin-bottom: 24px; border-bottom: 2px solid #0f62fe;
                 padding-bottom: 16px; }}
  h1 {{ font-size: 20px; font-weight: 800; color: #0f62fe; margin: 0; }}
  .meta {{ font-size: 11px; color: #6b7280; margin-top: 4px; }}
  .footer {{ margin-top: 32px; border-top: 1px solid #e5e7eb;
             padding-top: 12px; text-align: center;
             font-size: 11px; color: #9ca3af; }}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header-row">
    <div>
      <h1>i3 AgentOps — Weekly Review Pack</h1>
      <p class="meta">Week: <strong>{html.escape(week)}</strong>
        &nbsp;|&nbsp; Tenant scope: <strong>{html.escape(scope)}</strong>
        &nbsp;|&nbsp; Generated: {html.escape(generated_at[:19].replace("T"," "))} UTC
      </p>
    </div>
    <div style="font-size:11px;color:#6b7280;text-align:right;">
      Replaces ad-hoc status meetings.<br>
      Distribute to: Platform Ops, CTO, Tenant leads.
    </div>
  </div>

  {s1}
  {s2}
  {s3}
  {s4}
  {s5}
  {s6}

  <div class="footer">
    Generated by i3 AgentOps · IBM Bob &nbsp;|&nbsp;
    {html.escape(generated_at[:10])} &nbsp;|&nbsp;
    {html.escape(week)}
  </div>
</div>
</body>
</html>"""
