apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawa-data
  namespace: i3-pmaas
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuru-data
  namespace: i3-engage
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfumo-data
  namespace: i3-afroerp
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
