apiVersion: v1
kind: Secret
metadata:
  name: afroerp-secrets
  namespace: i3-afroerp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: aTMtTWFyaWFkYi1SMDB0LTIwMjYh
  MYSQL_PASSWORD: aTMtRnJhcHBlLURCLTIwMjYh
  MYSQL_USER: ZnJhcHBl
  MYSQL_DATABASE: YWZyb2VycA==
  ADMIN_PASSWORD: aTMtRVJQLUFkbWluLTIwMjYh
  SECRET_KEY: aTMtRVJQLVNlY3JldC1BQkNERUYxMjM0NTY3ODkwWFk=
  LITELLM_URL: aHR0cDovL2xpdGVsbG0tcHJveHkuaTMtbW9kZWwtZ2F0ZXdheS5zdmMuY2x1c3Rlci5sb2NhbDo0MDAwL3Yx
  KRA_API_URL: aHR0cHM6Ly9ldGltcy1hcGkua3JhLmdvLmtl
  KRA_CLIENT_ID: UkVQTEFDRQ==
  KRA_CLIENT_SECRET: UkVQTEFDRQ==
  KRA_PIN: UkVQTEFDRQ==
  MPESA_CONSUMER_KEY: UkVQTEFDRQ==
  MPESA_CONSUMER_SECRET: UkVQTEFDRQ==
  MPESA_PASSKEY: UkVQTEFDRQ==
  MPESA_SHORTCODE: UkVQTEFDRQ==
  LITELLM_KEY: UkVQTEFDRV9XSVRIX0xJVEVMTE1fTUFTVEVSX0tFWQ==
