apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
  namespace: i3-model-gateway
type: Opaque
data:
  LANGFUSE_PUBLIC_KEY: cGstbGYtaTNldmFsb3MtOGVkMjk5OGMzZjY4NDQ5Yg==
  LANGFUSE_SECRET_KEY: c2stbGYtaTNldmFsb3MtYjc5MDVlYWY0OTkwNGNjNQ==
  LITELLM_MASTER_KEY: REDACTED-b64-litellm
  WATSONX_API_KEY: UkVNT1ZFRA==
  WATSONX_PROJECT_ID: UkVNT1ZFRA==
  DATABASE_URL: cG9zdGdyZXNxbDovL2xpdGVsbG06c2stTGl0ZUxMTS1QRy0yMDI2LVNlY3VyZUBpMy1wb3N0Z3Jlcy1wZ2JvdW5jZXIuaTMtZGF0YS5zdmM6NTQzMi9saXRlbGxtX2RiP3BnYm91bmNlcj10cnVlJmNvbm5lY3Rpb25fbGltaXQ9NQ==
