apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voice-stt-models
  namespace: i3-voice
  labels:
    app.kubernetes.io/part-of: i3-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
